syntax = 'proto3';

package thesis.v1;

service ThesisService {
  rpc CreateThesis(GenerateThesesRequest) returns (GenerateThesesResponse);
  rpc GenerateAnswer(GenerateAnswerRequest) returns (GenerateAnswerResponse);
}

message Thesis{
  string value = 1;
  string importance = 2;
}

message GenerateThesesRequest {
  string question = 1;
  string answer = 2;
}

message GenerateThesesResponse {
  repeated Thesis theses = 1;
}

message GenerateAnswerRequest {
  string question = 1;
}

message GenerateAnswerResponse {
  string answer = 1;
}