syntax = "proto3";

package study.ticket.progress.v1;

import "google/protobuf/timestamp.proto";

service StudyTicketProgressService {
  rpc FindOneTicketProgress(FindOneTicketProgressRequest) returns (FindOneTicketProgressResponse);
  rpc FindAllTicketProgress(FindAllTicketsProgressRequest) returns (FindAllTicketsProgressResponse);
  rpc BatchTicketProgressBySubjects(BatchTicketProgressBySubjectsRequest) returns (FindAllTicketsProgressResponse);
  rpc FindDueTicketsProgress(FindDueTicketsProgressRequest) returns (FindDueTicketsProgressResponse);
}

message TicketProgress {
  string id = 1;
  string ticket_id = 2;
  string user_id = 3;
  string subject_id = 4;
  int32 total_count = 5;
  float best_score = 6;
  float last_score = 7;
  float average_score = 8;
  google.protobuf.Timestamp created_at = 9;
  google.protobuf.Timestamp updated_at = 10;
  google.protobuf.Timestamp due = 11;
  float stability = 12;
  float difficulty = 13;
  int32 elapsed_days = 14;
  int32 schedule_days = 15;
  int32 learning_steps = 16;
  int32 reps = 17;
  int32 lapses = 18;
  int32 state = 19;
  google.protobuf.Timestamp last_review = 20;
}

message FindOneTicketProgressRequest {
  string ticket_id = 1;
  string subject_id = 2;
  string user_id = 3;
}
message FindOneTicketProgressResponse {
  TicketProgress ticket_progress = 1;
}

message FindAllTicketsProgressRequest {
  string subject_id = 1;
  string user_id = 2;
}
message FindAllTicketsProgressResponse {
  repeated TicketProgress tickets_progress = 1;
}

message BatchTicketProgressBySubjectsRequest {
  string user_id = 1;
  repeated string subject_ids = 2;
}

message FindDueTicketsProgressRequest {
  string user_id = 1;
  string subject_id = 2;
  optional int32 limit = 3;
  optional int32 offset = 4;
}

message FindDueTicketsProgressResponse {
  repeated TicketProgress ticket_progress = 1;
}