/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UAvatarGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue')['default']
    UBreadcrumb: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UEditor: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Editor.vue')['default']
    UEditorDragHandle: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/EditorDragHandle.vue')['default']
    UEditorEmojiMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/EditorEmojiMenu.vue')['default']
    UEditorMentionMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/EditorMentionMenu.vue')['default']
    UEditorSuggestionMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/EditorSuggestionMenu.vue')['default']
    UEditorToolbar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/EditorToolbar.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULink: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/vue/overrides/vue-router/Link.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPopover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    UProgress: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USkeleton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_a5f419b0af6951d853e629ca1e0dd9cb/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
