syntax = "proto3";

package ticket.v1;

import "content/common.proto";
import "google/protobuf/timestamp.proto";

service TicketService {
  rpc CreateTicket(CreateTicketRequest) returns (TicketResponse);
  rpc FindAllTickets(FindAllTicketsRequest) returns (FindAllTicketsResponse);
  rpc FindOneTicket(FindOneTicketRequest) returns (TicketResponse);
  rpc PatchTicket(PatchTicketRequest) returns (TicketResponse);
  rpc DeleteTicket(DeleteTicketRequest) returns (common.content.v1.SuccessResponse);

  // Метод для (пере)генерации тезисов через ИИ
  rpc GenerateTheses(GenerateThesesRequest) returns (TicketResponse);

  // Метод для генерации ответа на вопрос через ИИ
  rpc GenerateAnswer(GenerateAnswerRequest) returns (GenerateAnswerResponse);
}

// Сущность тезиса для использования в ответах
enum Importance {
  LOW = 0;
  MEDIUM = 1;
  HIGH = 2;
}

message Thesis {
  string id = 1;
  string value = 2; // Сам тезис
  Importance importance = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
}

message ThesisInput {
  string value = 1;
  Importance importance = 2;
  optional string id = 3;
}

// Основной объект билета
message Ticket {
  string id = 1;
  string subject_id = 2;
  string question = 3;
  string answer = 4;
  repeated Thesis theses = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
}

// Сообщения для RPC
message CreateTicketRequest {
  string subject_id = 1;
  string question = 2;
  string answer = 3;
  repeated ThesisInput theses = 4;
}

message TicketResponse {
  Ticket ticket = 1;
}

message FindAllTicketsRequest {
  string subject_id = 1; // Чтобы найти все билеты конкретного предмета
  optional int32 limit = 2;
  optional int32 offset = 3;
}

message FindAllTicketsResponse {
  repeated Ticket tickets = 1;
  int32 totalCount = 2;
}

message FindOneTicketRequest {
  string id = 1;
  string user_id = 2;
}

message ThesisInputList {
  repeated ThesisInput items = 1;
}
message PatchTicketRequest {
  string id = 1;
  string user_id = 2;
  optional string question = 3;
  optional string answer = 4;
  optional ThesisInputList theses = 5;
}

message DeleteTicketRequest {
  string id = 1;
  string user_id = 2;
}

// Запрос на генерацию тезисов
message GenerateThesesRequest {
  string ticket_id = 1;
  string question = 2;
  string answer = 3;
}

// Генерация ответа на вопрос
message GenerateAnswerRequest {
  string question = 1;
}

message GenerateAnswerResponse {
  string answer = 1;
}
