name: Backend CI

on:
  push:
    branches: [main, master]
    paths:
      - 'cogna.backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [main, master]
    paths:
      - 'cogna.backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cogna.backend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Установка pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Использование Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
#          cache: 'pnpm'
#          cache-dependency-path: 'cogna.backend/pnpm-lock.yaml'

#      - name: Установка зависимостей
#        run: pnpm install --frozen-lockfile

#      - name: Линтинг
#        run: pnpm lint
#
#      - name: Проверка типов
#        run: pnpm typecheck

      # - name: Запуск тестов
      #   run: pnpm test

      # - name: Создание отчета о покрытии
      #   run: pnpm test:cov

#      - name: Загрузка отчета о покрытии
#        uses: codecov/codecov-action@v3
#        with:
#          files: ./cogna.backend/coverage/coverage-final.json
#          flags: unittests
#          name: codecov-umbrella
#          fail_ci_if_error: false
